### ISSUE TITLE
Error in Precognition React using Sanctum

### ISSUE THREAD

**Issue by joaopalopes24** [laravel/precognition#53]
### Laravel Precognition Plugin Version

0.5.2

### Laravel Version

10.31.0

### Plugin

React

### Description

I installed Laravel Breeze API and create the login component in React.

api:
```
import axios from "axios";
import { config } from "@/config/config";

function client(baseURL: string | undefined) {
  const client = axios.create({ baseURL, withCredentials: true });

  client.defaults.headers.common["Accept"] = "application/json";
  client.defaults.headers.common["Content-Type"] = "application/json";

  return client;
}

const api = client(config.NEXT_PUBLIC_API_URL);

export default api;
```

sanctumRepository:
```
import api from '@/services/api';

export const csrf = () => api.get('/sanctum/csrf-cookie');
```

login:
```
  client.use(api);

  const form = useForm("post", "/login", {
    email: "",
    password: "",
    remember: false,
  });

  const submit = async (e: any) => {
    e.preventDefault();

    await csrf();

    form
      .submit()
      .then((data) => {
        console.log(data);
      })
      .catch((error) => {
        console.log(error);
      });
  };
```

Error:
```
{
    "message": "CSRF token mismatch.",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\HttpException",
    "file": "/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php"
}
```

### Steps To Reproduce

Install Laravel Breeze API and try to use Precognition React.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
@joaopalopes24 feel free to reopen this once you have a repo available. Thanks

**Comment by timacdonald** [comment]
@joaopalopes24 I can see that you retrieve the CSRF token from the API, but I don't see that you actually give it to precognition / Axios anywhere?

Assuming that `await csrf();` returns the CSRF token...

```js
import { client } from 'laravel-precognition-vue';

client.axios().defaults.headers.common['X-CSRF-TOKEN'] = await csrf();
```
