### ISSUE TITLE
onValidate callback or async validate (reopen)

### ISSUE THREAD

**Issue by joncarlson** [laravel/precognition#59]
This was opened from #56 which I think was inadvertently closed, as it didn't have a resolution. The linked issues have similar questions which I haven't found an answer to yet.

Following is the text of the original issue. I'd be happy to contribute a PR for this, but would like to know if the proposed solution below is a good one or if there is a plan to handle this.

Because a validate does a roundtrip to the server, it would be nice to know when that roundtrip is finished.

For example, we have a multi-step form. The fields in each step need to be valid before being able to proceed to the next step.

I would think adding a couple options to the .validate(), similar to the .submit(), would be a great addition, something like:

form.validate(id, { onValidated: function(isValid: boolean) {} })

Thank you

**Comment by timacdonald** [comment]
Hey, there, this is on our radar and something we plan on adding in the coming month. Will update when I have a PR available.

**Comment by mreduar** [comment]
> This is on our radar and something we plan on adding in the coming month. Will update when I have a PR available.

Nice!

**Comment by djurovicigoor** [comment]
Hello, any news on this?

**Comment by timacdonald** [comment]
Hey folks, I've been working on this one and I'm pretty close to having something I'm happy with.

Something I ran into today is a debouncing issue. We debounce the `validate` method, so it often returns the same promise. In the following example, if I were to type `abcdef` into an input field it would run the console log 6 times when the request resolves.

```
@input="form.validate('name').then(() => console.log('done')"
```

That feels unexpected to me, so I'm investigating some other solutions, such as [Awesome Debounce Promise](https://www.npmjs.com/package/awesome-debounce-promise) which allows you to debounce with a promise but only keep the lastest "thenables" called against the promise.

If anyone has any thoughts on that, I'm open to suggestions, otherwise I'll keep digging in that direction.

**Comment by mreduar** [comment]
> If anyone has any thoughts on that, I'm open to suggestions, otherwise I'll keep digging in that direction.

Since I use vue I usually [useDebounceFn](https://vueuse.org/shared/useDebounceFn/) and [useThrottleFn](https://vueuse.org/shared/useThrottleFn/) in cases like that. Although [Lodash debounce](https://lodash.com/docs/4.17.15#debounce) is almost the same, I like to use the vueuse ones better. Maybe they can give you a clue on how to solve your problem even without any dependency.

**Comment by timacdonald** [comment]
Got a working version of this I'm happy with (without any packages).

Should have a complete PR up on Monday and would love feedback and testing from anyone interested.

**Comment by djurovicigoor** [comment]
Hey! Any news on this?

**Comment by timacdonald** [comment]
Lots of action over here: https://github.com/laravel/precognition/pull/69

**Comment by timacdonald** [comment]
I'm going to close this one and we can follow #69. I'm in the testing phase on this PR to ensure it does exactly what we need.

Thanks for your patience on this one. Required me to rethink how Precognition worked a bit to make it really seamless.

**Comment by timacdonald** [comment]
Opened for review: https://github.com/laravel/precognition/pull/69

**Comment by timacdonald** [comment]
Merged and tagged.

```vue
<TextInput
    v-model="form.name"
    @change="form.validate('name', {
        onSuccess: () => /* ... */,
        onValidationError: () => /* .. */,
    })"
/>
```
